Sourabha G student report
sugarlabs/GSoC pull request #136
Opened 2021-08-21 09:02 UTC by sourabhaa

2021-08-21 10:48 UTC, srevinsaju requested changes
Nice write up, few typos.

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +My work mostly revolove around adding basic game design features, porting activities to python3, test the activities in development environment and user environment(kids). Project also includes addin
Typo in revolve

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +My work mostly revolove around adding basic game design features, porting activities to python3, test the activities in development environment and user environment(kids). Project also includes addin
Also, typo in `fetiching -> fetching`

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +|JAMath activitty|Changed flow of activity by addding game-design features: <ul><li>A UI that shows the `score`, `highscore` of the player which decides the `win`/`lose`, `replay` and `exit` buttons
Typo in `activity`

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +| Recall activity | Changed flow of activity by addding game-design features: <ul><li>A UI that shows the `score`, `highscore` of the player which decides the `win`/`lose` after completion of each ga
Typo in `adding`

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +| Clasify-cats |Work on this activity is completed, release PR yet to be reviewed.<br>Changed flow of activity by addding game-design features: <ul><li>Added scoring system</li><li>A UI that shows th
Typo in adding.

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +|Flip|(Open PR) The release of this activity is temporarily blocked by the feature 'save and restore game data from `Journal`'<br>Changed flow of activity by addding game-design features: <ul><li>A U
Typo in adding

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +This summer was super fun and filled with learning! I enjoyed testing over 60+ activities with kids to get first-hand feedback which had a postive impact in the way they apprach problems. The fact th
typo in approach

2021-08-21 10:48 UTC, srevinsaju commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +This summer was super fun and filled with learning! I enjoyed testing over 60+ activities with kids to get first-hand feedback which had a postive impact in the way they apprach problems. The fact th
For consistency, use "Sugar Labs"

2021-08-21 17:32 UTC, quozl commented
Reviewed.  Acceptable as is.  If you have time for refinement, consider checking tense and rewriting in past tense where possible.  Also a few opportunities for punctuation and whitespace following international english conventions.

2021-08-22 16:33 UTC, chimosky requested changes

2021-08-22 16:33 UTC, chimosky commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +Improve and maintain atleast 15 Sugar Activities
The project title is **Improve and Maintain 15 Activities**, no _atleast_.

2021-08-22 16:33 UTC, chimosky commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +| Recall activity | Changed flow of activity by addding game-design features: <ul><li>A UI that shows the `score`, `highscore` of the player which decides the `win`/`lose` after completion of each ga
Repetition of `per game`. 

`Automatic restart the game after Gameover UI` should be `Automatically restart the game after gameover.`

2021-08-22 16:40 UTC, chimosky requested changes

2021-08-22 16:40 UTC, chimosky commented on archives/2021/student-reports/improve-and-maintain-15-activities-Sourabha-G.md
> +This summer was super fun and filled with learning! I enjoyed testing over 60+ activities with kids to get first-hand feedback which had a postive impact in the way they apprach problems. The fact th
Typo in `I'm going continue` should be `I'm going to continue`.

2021-08-22 16:43 UTC, chimosky commented
Reviewed and I agree with @quozl above. Thanks for your work with the community.

2021-08-22 16:43 UTC, merged